version: 2
  jobs:

    build:
      name: Deploy to Sourcepad ECS
      working_directory: ~/training
      docker:
        - image: circleci/ruby:latest
      steps:
        - checkout
        - run: script/ecs-deploy.sh staging
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy

