version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    working_directory: ~/training
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build trainees docker image
          command: |
            TAG=$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
            docker build -t dockerfordevs:latest ~/training/
      - run:
          name: Check the answers!
          command: |
            env ANSWER=$ANSWER2 sh ./checker.sh
