version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    working_directory: /training
    steps:
      - checkout
      - setup_remote_docker:
        docker_layer_caching: true
      - run:
          - name: Build trainees docker image
          - command: |
              TAG=$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
              docker build -t dockerfordevs:$TAG
      - run:
          - name: Run trainees docker image
          - command: |
              docker run --name dockerfordevs$TAG dockerfordevs:$TAG
      - run:
          - name: Health check!
          - command: |
              echo | docker exec dockerfordevs$TAG curl -sb -H http://0.0.0.0
